// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezgiwbdpayziybpwamam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6Z2l3YmRwYXl6aXlicHdhbWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjc0ODksImV4cCI6MjA3MDYwMzQ4OX0.kkX82xNbtniBw0PtJ7xl_Ju7ti9tWLvyXsduil76WTk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});